const videoMock = {
  womContentId: '5dde5d262b7e855858284e5b',
  title: 'Some title',
  tags: ['helloworld', 'some', 'anotherone'],
  streamDetails: {
    thumbnailUrl: 'https://cloudflarestream.com/5be7bf0870451ad75e87e0e6a05adccc/thumbnails/thumb_5_0.jpg',
    animatedUrl: 'https://videodelivery.net/5be7bf0870451ad75e87e0e6a05adccc/thumbnails/thumbnail.gif?duration=10s',
  },
  products: [
    {
      id: '   ',
      brandName: 'Adidas',
      item: 'Superstar',
      tagBrand: 'Adidas',
      tagCategory: 'Shoes',
      tagSubCategory: 'Sport Shoes',
      extraTags: ['extraone', 'extratwo', 'extrasome', 'extranother'],
    },
  ],
  womQualityScore: {
    authenticity: 7.8,
    creativity: 8.5,
    positivity: 9.2,
    quality: 0,
  },
  engagement: {
    views: 0,
    viewsD1: 0,
    viewsD1Percentage: 0,
    viewsD2: 0,
    viewsD2Percentage: 0,
    viewsD3: 0,
    viewsD3Percentage: 0,
    viewsD4: 0,
    viewsD4Percentage: 0,
    likes: 0,
    likesPercentage: 0,
    ratings: 0,
    ratingsPercentage: 0,
    saves: 0,
    savesPercentage: 0,
    shares: 0,
    sharesPercentage: 0,
    clicks: 0,
    clicksPercentage: 0,
    buys: 0,
    buysPercentage: 0,
    finalTotal: 0,
  },
};

export default videoMock;
