export const CAMPAIGN_SET_LIST_TO_PAGE = 'CAMPAIGN_SET_LIST_TO_PAGE';
export const CAMPAIGN_SET_CURRENT_PAGE = 'CAMPAIGN_SET_CURRENT_PAGE';
export const CAMPAIGN_SET_STAT_INFO = 'CAMPAIGN_SET_STAT_INFO';
export const CAMPAIGN_SYNC_ONE = 'CAMPAIGN_SYNC_ONE';
