# Using the node alpine image to build the React app
image: node:alpine

# Cache node modules - speeds up future builds
cache:
    paths:
        - node_modules

# Name the stages involved in the pipeline
stages:
    - lint/build
    - build/deploy-stage
    - build/deploy-prod

lint/build:
    stage: lint/build
    script:
        - echo "Linting"
        - yarn
        - yarn lint
        - echo "Linting successful"
        - echo "Building deploy package"
        - yarn build:stage
        - echo "Build successful"
    only:
        - merge_requests

build/deploy-prod:
    stage: build/deploy-prod
    before_script:
        - apk update
        - apk add --update --no-cache openssh sshpass
        - export SSHPASS=$SSH_PRIVATE_KEY
    script:
        - echo "Building deploy package"
        - yarn
        - yarn build:prod
        - echo "Build successful"
        - echo "Deploying to server"
        - echo > pk.txt "$SSH_PRIVATE_KEY" | tr -d '\r'
        - chmod 400 pk.txt
        - chmod -R 755 build
        - sshpass scp -i pk.txt -P 1122 -o stricthostkeychecking=no -r build/* campaign@stage-srv.xc.io:~/campaign/
        - echo "Deployed"
    only:
        - master
    when: manual

build/deploy-stage:
    stage: build/deploy-stage
    before_script:
        - apk update
        - apk add --update --no-cache openssh sshpass
        - export SSHPASS=$USER_PASS_ICWT
    script:
        - echo "Building deploy package"
        - yarn
        - yarn build:stage
        - echo "Build successful"
        - echo "Deploying to ICWT server"
        - sshpass -e scp -o stricthostkeychecking=no -r ./build/* $USER_ICWT@$HOST_ICWT:$TARGET_DIR_ON_HOST_ICWT
    only:
        - master
