# Using the node alpine image to build the React app
image: node:14-alpine

# Cache node modules - speeds up future builds
cache:
    paths:
        - node_modules

# Name the stages involved in the pipeline
stages:
    - lint/build
    - build/deploy-stage-dev
    - build/deploy-stage-prod
    - build/deploy-prod

lint/build:
    stage: lint/build
    before_script:
        - apk update
        - apk add --no-cache make g++
    script:
        - echo "Linting"
        - yarn
        - yarn lint
        - echo "Linting successful"
        - echo "Building deploy package"
        # * react-scripts
        - yarn build:stage
        # * vite
        # - yarn build:vite:stage
        - echo "Build successful"
    only:
        - merge_requests

build/deploy-stage-dev:
    stage: build/deploy-stage-dev
    variables:
        SERVER: '$USER_DO@$HOST_DO'
    before_script:
        - apk update
        - apk add --update --no-cache openssh sshpass
        - apk add --no-cache make g++
        - export SSHPASS=$USER_PASS_DO
    script:
        - echo "Building dev version deploy package"
        - yarn
        # * react-scripts
        - yarn build:stage
        # * vite
        #- yarn build:vite:stage
        - echo "Build successful"
        - echo "Deploying to DO (dev droplet) server"
        - sshpass -e ssh -p 22 -oStrictHostKeyChecking=no -tt "$SERVER" 'rm -rf "$TARGET_DIR_ON_DO_FOR_DEV"/static'
        - sshpass -e scp -P 22 -o stricthostkeychecking=no -r build/* "$SERVER":"$TARGET_DIR_ON_DO_FOR_DEV"
        - echo "Deployed"
    only:
        - master

build/deploy-stage-prod:
    stage: build/deploy-stage-prod
    variables:
        SERVER: '$USER_DO@$HOST_DO'
    before_script:
        - apk update
        - apk add --update --no-cache openssh sshpass
        - apk add --no-cache make g++
        - export SSHPASS=$USER_PASS_DO
    script:
        - echo "Building dev version deploy package"
        - yarn
        # * react-scripts
        - yarn build:prod
        # * vite
        #- yarn build:vite:stage
        - echo "Build successful"
        - echo "Deploying to DO server"
        - sshpass -e ssh -p 22 -oStrictHostKeyChecking=no -tt "$SERVER" 'rm -rf "$TARGET_DIR_ON_DO_FOR_PROD"/static'
        - sshpass -e scp -P 22 -o stricthostkeychecking=no -r build/* "$SERVER":"$TARGET_DIR_ON_DO_FOR_PROD"
        - echo "Deployed"
    only:
        - master

build/deploy-prod:
    stage: build/deploy-prod
    before_script:
        - apk update
        - apk add --update --no-cache openssh sshpass
        - apk add --no-cache make g++
        - export SSHPASS=$SSH_PRIVATE_KEY
    script:
        - echo "Building deploy package"
        - yarn
        # * react-scripts
        - yarn build:prod
        # * vite
        #- yarn build:vite:prod
        - echo "Build successful"
        - echo "Deploying to server"
        - echo > pk.txt "$SSH_PRIVATE_KEY" | tr -d '\r'
        - chmod 400 pk.txt
        - chmod -R 755 build
        - sshpass scp -i pk.txt -P 1122 -o stricthostkeychecking=no -r build/* campaign@stage-srv.xc.io:/home/campaign/campaign/
        - echo "Deployed"
    only:
        - tags
        - ^WMCM-BUILD-[0-9].[0-9]+.[0-9]$
    when: manual
