export const USERS_SET_LIST_TO_PAGE = 'USERS_SET_LIST_TO_PAGE';
export const USERS_SET_CURRENT_PAGE = 'USERS_SET_CURRENT_PAGE';
export const USERS_SYNC_ONE = 'USERS_SYNC_ONE';
export const USERS_REMOVE = 'USERS_REMOVE';
