export const DISCOVER_SET_LIST_TO_PAGE = 'DISCOVER_SET_LIST_TO_PAGE';
export const DISCOVER_SET_CURRENT_PAGE = 'DISCOVER_SET_CURRENT_PAGE';
export const DISCOVER_SYNC_ONE_VIDEO = 'DISCOVER_SYNC_ONE_VIDEO';
